---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    dest: "/etc/hosts"
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 {{ inventory_hostname }} localhost"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Set server locale
  locale_gen:
    name: "en_US.UTF-8"

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade apt packages to the latest safe versions
  apt:
    upgrade: "safe"

- name: Install required packages
  apt:
    name:
      - "curl"
      - "gnupg2"
      - "git"
      - "lnav"
      - "sudo"
      - "unattended-upgrades"
      - "apt-listchanges"
      - "ufw"
      - "systemd-timesyncd"
      - "postgresql"
      - "python3-psycopg2"

# without this, there was an error when enabling the firewall:
# ERROR: problem running ufw-init
# ip6tables-restore: line 4 failed
# ip6tables-restore: line 65 failed
# Problem running '/etc/ufw/before6.rules'

# Use hardware firewall

- name: Disable IPv6 in UFW
  lineinfile:
    path: "/etc/default/ufw"
    regexp: "^IPV6="
    line: "IPV6=no"

- name: Open SSH port in firewall
  ufw:
    rule: "allow"
    port: "ssh"
    proto: "tcp"

- name: Start firewall with default rule deny and disable logging
  ufw:
    state: "enabled"
    policy: "deny"
    logging: "off"

# UNATTENDED UPGRADES
# https://wiki.debian.org/UnattendedUpgrades

- name: configure unattended upgrades
  shell: "echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections"

- name: enable unattended upgrades
  shell: "dpkg-reconfigure -f noninteractive unattended-upgrades"

- name: enable daily apt tasks and timers
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: "started"
    masked: no
  with_items:
    - "apt-daily.service"
    - "apt-daily-upgrade.service"
    - "apt-daily.timer"
    - "apt-daily-upgrade.timer"

# Time

- name: set /etc/timezone to Europe/Helsinki
  copy:
    content: "Europe/Helsinki"
    dest: "/etc/timezone"
  notify: update tzdata

- name: symlink /etc/localtime
  file:
    src: "/usr/share/zoneinfo/Europe/Helsinki"
    path: "/etc/localtime"
    state: "link"
  notify: update tzdata

- name: enable systemd-timesyncd
  systemd:
    name: "systemd-timesyncd"
    enabled: yes

- name: configure systemd-timesyncd to use NTP servers
  lineinfile:
    path: "/etc/systemd/timesyncd.conf"
    regexp: "^#?NTP="
    line: "NTP=0.fr.pool.ntp.org 1.fr.pool.ntp.org 2.fr.pool.ntp.org 3.fr.pool.ntp.org"
  notify: "restart systemd-timesyncd"
